version: '3.7'


services:
    rabbitmq:
        restart: always
        image: rabbitmq:3.8.6
        expose:
            - '5672'
        volumes:
          - rabbitmq:/var/lib/rabbitmq
        env_file:
          - .env

    web:
        restart: always
        build: .
        ports:
            - '8000:8000'
        volumes:
            - ./app:/app
        env_file: .env
        depends_on:
            - rabbitmq
        command: python main.py

    worker:
        build: .
        depends_on:
            - rabbitmq
        env_file: .env
        volumes:
            - ./app:/app
        command: celery -A main.celery worker -l info

volumes:
    rabbitmq:
