version: '3.7'


services:
    rabbitmq:
        restart: always
        image: rabbitmq:3.8.6
        expose:
            - '5672'
        ports:
            - '5672:5672'    
        volumes:
          - rabbitmq:/var/lib/rabbitmq
        env_file:
          - .env
            #        ports:
            #            - '5000:5000'
            #        volumes:
            #            - ./app:/app
            #        env_file: .env
            #        depends_on:
            #            - rabbitmq
            #
            #        command python main.py



volumes:
    rabbitmq:
